version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: programming-php
    restart: always
    working_dir: /var/www/
    volumes:
        - ../src:/var/www
  nginx:
    image: nginx:1.9-alpine
    container_name: programming-nginx
    restart: always
    ports:
      - "8051:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: programming-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306